### ISSUE TITLE
Implementation of Exercise_08_c

### ISSUE THREAD

**Issue by EverLookNeverSee** [EverLookNeverSee/FCS#1]
![imgonline-com-ua-twotoone-tIdq3xAgq5O2B](https://user-images.githubusercontent.com/57490926/83945887-ca068200-a822-11ea-9535-5f21773a2832.png)

**Comment by LKedward** [comment]
I think `m=2` and `z=0.75` perhaps?

**Comment by EverLookNeverSee** [comment]
> I think `m=2` and `z=0.75` perhaps?

How?

**Comment by LKedward** [comment]
Sorry, I should have explained that a bit more.

```
x = z*(2^m)
```

therefore

```
z = x/(2^m)
```

we can choose any `m` as long as `-1 < z < 1`.

Questions asks for x=3, for which `m=2` and `z=0.75` works.

Possible pseudo-code for program:

```
set ln2 = 0.6931472
ask user for value of x
ask user for value of m
calculate z = x/(2^m)
check that -1 < z < 1

calculate xi= (1-z)/(1+z)
calculate lnx = m*ln2 - 2*sum( (xi^(1:N))/(1:N) )

compare with exact value of ln(x)
```

Can try different values of `m` - I think smaller `m` will give a larger `z` which will give a smaller `xi` which will lead to fewer terms necessary for a certain precision.

Hope that helps a bit more.

**Comment by EverLookNeverSee** [comment]
Thank you very much @LKedward

**Comment by FortranFan** [comment]
@EverLookNeverSee ,

Can you provide a reference to a derivation for the relationship you show in the original post?

A quick glance suggests the series is **divergent** for z <= 0, so a numerical approach is unclear for -1 <= z <= 0.

When z > 0, xi < 1, so one can compute the series numerically to determine lnx.

**Comment by LKedward** [comment]
@FortranFan, the exercises appear to be from: Bose, S., 2019. _Numerical Methods Of Mathematics Implemented In Fortran_. Singapore. Springer. See [here on google](https://books.google.co.uk/books?id=PLuXDwAAQBAJ&pg=PA55&dq=compute+the+following+infinite+series+by+writing+Fortran+program&source=gbs_toc_r&cad=3#v=onepage&q=compute%20the%20following%20infinite%20series%20by%20writing%20Fortran%20program&f=false).

The text does not provide a derivation for the relation; my summary conclusion is that it is an error since `z <= 0` implies `x <= 0` which would be problematic for then calculating `ln(x)`.
As you point out, `0 < z <= 1` appear to be the correct bounds for `z` here.

**Comment by RonShepard** [comment]
One derivation of the relation in the original post follows from the identities

     y(z) = (1-z)/(1+z)

    z(y) = (1-y)/(1+y)

From this, it follows that

   ln(z) = ln(1-y) - ln(1+y)

Taylor expansion at y=0 on the right then gives the result shown in the original post where all of the even terms vanish. The radius of convergence of ln() on the right is -1<y<1. However, convergence is slow for large |y|, so the only useful values for computation are when y is small, which is when z is near +1. Thus in the computation where x is given, m should be chosen to make z<=1 as close to 1 as possible.
