### ISSUE TITLE
BUG - Cardano's solution returns wrong answer

### ISSUE THREAD

**Issue by EverLookNeverSee** [EverLookNeverSee/FCS#4]
For a_1 = 1, a_2 = 2, a_3 = 3 ,
it should print
x_1 = -1.27568
z_2 = 0.13784 + i * 1.52731
z_3 = 0.13784 - i * 1.52731
But it prints
x_1 = -2.58565688
z_2 =  ( 0.792838216    , -2.33903098    )
z_3 =  ( 0.792719483    ,  2.33903098    )

I think the error might be at **sign** section of code:
https://github.com/EverLookNeverSee/FCS/blob/acb60b0728226dfd4508fa420787b606294a74ba/src/numerical%20methods/Exercise_14.f90#L36

**Comment by EverLookNeverSee** [comment]
@LKedward Do you have any idea about this?

**Comment by LKedward** [comment]
Hi @EverLookNeverSee , I've been through the code and run it on my computer and I can't find any mistake with respect to the [formulae you are referencing](https://fortran-lang.discourse.group/t/cardanos-solution-of-the-cubic-equation/111) .
(As you point out, the code still doesn't return the correct result with `sign(1.0,R)`.)

_i.e._ I believe you have implemented the formulae correctly, so I wonder whether there's a mistake in the formulae?
Unfortunately I can't verify the formulae since I can't find a reference online that formulates Cardano's method in the same way as here - I would recommend either verifying the formulae from another source or working off a different set of formulae.

**Comment by EverLookNeverSee** [comment]
> Hi @EverLookNeverSee , I've been through the code and run it on my computer and I can't find any mistake with respect to the [formulae you are referencing](https://fortran-lang.discourse.group/t/cardanos-solution-of-the-cubic-equation/111) .
> (As you point out, the code still doesn't return the correct result with `sign(1.0,R)`.)
> 
> _i.e._ I believe you have implemented the formulae correctly, so I wonder whether there's a mistake in the formulae?
> Unfortunately I can't verify the formulae since I can't find a reference online that formulates Cardano's method in the same way as here - I would recommend either verifying the formulae from another source or working off a different set of formulae.

Thank you very much

**Comment by EverLookNeverSee** [comment]
@LKedward 
I found solution below and would like to use it:
![Screenshot_20200613_172111](https://user-images.githubusercontent.com/57490926/84569260-689e6000-ad9a-11ea-9f2f-ca803ec006ca.png)

**Comment by EverLookNeverSee** [comment]
### Solved!
